# Generated by Django 4.2.3 on 2023-08-04 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя Фамилия')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Электронная почта')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя на сайте')),
                ('phone', models.CharField(blank=True, max_length=60, null=True, verbose_name='Телефон')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация о пользователе')),
                ('account_image', models.ImageField(default='accounts/user-default.png', upload_to='accounts/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
