# Generated by Django 4.2.3 on 2023-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отдел, направление'),
        ),
        migrations.AddField(
            model_name='account',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
