# Generated by Django 4.2.3 on 2023-07-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_auto_20230627_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Лицензионный участок', 'verbose_name_plural': 'Лицензионные участки'},
        ),
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='area',
            name='num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='area',
            name='otvod',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отвод'),
        ),
        migrations.AlterField(
            model_name='area',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='area',
            name='seria',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='area',
            name='start',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Выдали'),
        ),
        migrations.AlterField(
            model_name='area',
            name='stop',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='area',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название ЛУ'),
        ),
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип'),
        ),
    ]
