# Generated by Django 4.2.3 on 2023-07-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0006_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='area',
            new_name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
