# Generated by Django 4.2.3 on 2023-08-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('centre', '0008_alter_report_options_report_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.account'),
        ),
        migrations.AlterField(
            model_name='report',
            name='field',
            field=models.CharField(max_length=60, verbose_name='Месторождение'),
        ),
    ]
