# Generated by Django 4.2.3 on 2023-08-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0009_report_owner_alter_report_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('telephone', models.CharField(max_length=20, verbose_name='Номер телефона рабочий')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Электронная почта')),
                ('office', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'список',
                'verbose_name_plural': 'Списки',
            },
        ),
    ]
