# Generated by Django 4.2.3 on 2023-08-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0010_department1'),
    ]

    operations = [
        migrations.AddField(
            model_name='department1',
            name='name',
            field=models.ManyToManyField(blank=True, to='centre.group', verbose_name='Отдел'),
        ),
    ]
