# Generated by Django 4.2.3 on 2023-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0013_directorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorate',
            name='image',
            field=models.ImageField(default='accounts/user-default.png', upload_to='accounts/'),
        ),
    ]
