# Generated by Django 4.2.3 on 2023-09-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0014_directorate_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'отчет', 'verbose_name_plural': 'Отчеты'},
        ),
    ]
