# Generated by Django 4.2.3 on 2023-09-04 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centre', '0015_alter_report_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=100, null=True, verbose_name='Месторождение')),
                ('purpose', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цель задачи')),
                ('number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер скважины')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('important', models.BooleanField(default=False, verbose_name='Срочность задачи')),
                ('name', models.ManyToManyField(blank=True, to='centre.group', verbose_name='Отдел для выполнения')),
                ('title', models.ManyToManyField(blank=True, to='centre.area', verbose_name='Лицензионный участок')),
                ('type', models.ManyToManyField(blank=True, to='centre.type', verbose_name='Вид работ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'задачу',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
