# Generated by Django 4.2.3 on 2023-09-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0016_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
    ]
