# Generated by Django 4.2.3 on 2023-09-04 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_options_account_department_and_more'),
        ('centre', '0018_bid_area_remove_bid_title_bid_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.account', verbose_name='Кто выполняет задачу'),
        ),
    ]
