# Generated by Django 4.2.3 on 2023-09-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0020_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон заявителя'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user_bid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя Фамилия заявителя'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цель заявки'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название заявки'),
        ),
    ]
